language: node_js
node_js:
  - 14
install:
  - npm install
before_script:
  - npm run lint
deploy:
  - provider: surge
    project: ./app/public/
    domain: projectkilogram.surge.sh
    skip_cleanup: trues
  - provider: heroku
    app: projectkilogram
    api_key:
      secure: "vPoH35bPqlbA8fW/8lmQwauee7eNeOwIk1YxzwgW85/+M1LdI1IH8JXIcmeWe28ETJVEIeM/daF0MofKrke13X+jQ1sUvooWW+BTFYxScJumJjOVvGNruJNzu4fNsGjuhm2alSKOIGjOFPBQ5bRoxX2vM/PgvdsyIu0fLivzYTlSV+UW7u/172IIPpc4ab7qpPQUGRE23+oIUnadXHHrUfJeyiUo9pAZD26YHxO2U9+UQ7JSnxVj+Om7/x5SK3HcVUKxDHd99Z9LUUbXSW5Nc9yqSqyFkPl7EeRx9k3tUWdkjma1eGmO85N6FRFtCKaQ5DMw8+D7oSQZxmRuCwXMFDd8njjW5R7NkJEMti9UzUQPPNKzUg4jNDAciFYcEInppS7wBTlCR1JWf+J6QInNWqXhV6/SKPGHkbivt8zDs11Kyuv02lf2R/zi1urxCJZspT9PS8xKRH0XI8zAFM7u7wFrC4M6fDrCTZEpcHUpDpGhXFx4UWQjfwmjudLdQQ+NFlA2/yHxGLI3f9WjGVDNrHgzfA3U11DSSvCw2ljtOqmLDtcRT/9A5xAtpVqO4Cb2YYerfGvRmexQ4raEi+M6MddFFU/6Tdc9cTPxCPQWdIQ5/EErv6hJNOhY5WsKE6UlgrOgKRIjGOmrVPCn3euF8JKLouSVWgRekEx1gEk6T5o="